server:
  port: 8989

spring:
  #开发库
  datasource:
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.122:3306/cc?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
  servlet:
    multipart:
      max-file-size: 20MB


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.cc.entity.*
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true















